In [2]:
import numpy as np

In [3]:
#creating n-array from list
arr= np.array([1,3,4,56,6])
print(arr,arr.shape)

[ 1  3  4 56  6] (5,)


In [4]:
#creating 2d array
arr2d= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d,arr2d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [5]:
# raetinf 2d arr by scratch
arr1= np.zeros((2,3)) # prefilled with the zeros
print(arr1,arr1.shape)

#with ones 
arr4= np.ones((2,3)) # prefilled with the zeros
print(arr4,arr4.shape)


arr5= np.full((2,3),100) # filled with the 100
print(arr5,arr5.shape)

arr3= np.eye(3) # identity matrix 
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
 #properties of numpy
arr= np.array([1,23,4])
print(arr.size)
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

3
int64
[ 1. 23.  4.] float64


In [7]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
reshaped=arr.reshape((3,2))# changeing the dimension of array
print(reshaped)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [8]:
#fancy indexing
arr= np.array([1,3,4,56,6])
idx=[0,1,3]
print(arr[idx])

[ 1  3 56]


In [9]:
#boolean indexing
print(arr[arr>2])
print(arr[arr%2==0])

[ 3  4 56  6]
[ 4 56  6]


In [10]:
#slicing of np aray
print(arr[1:4])
print(arr[::2])
print(arr[1:4:2])


#######NOTE#####
 # if we will do slicing in npython list so the list which see after
# slicing i a copy of the part of the list and it 
# takes a memory in system where as in numpy list it show you only 
# original values no other copy i formed so that why numpy array is fast 


[ 3  4 56]
[1 4 6]
[ 3 56]


In [11]:
#Data Types
arr = np.array([1, 2, 3.14, 4, 5])
print(arr, arr.dtype)

[1.   2.   3.14 4.   5.  ] float64


In [12]:
 # Multi-dimensional arrays
arr2D= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)
print(np.sum(arr2D))
sum_of_columns = np.sum(arr2D, axis =0)
print(sum_of_columns)
print(arr2d[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[[2]
 [5]]


In [15]:
 #3D array
arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]]) #2 x 3 x 2
print(arr3D, arr3D.shape)
#indexing
print(arr3D [1, 1, 0])
print(arr3D[:,:,0])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[ 1  3  5]
 [ 7  9 11]]


In [16]:
#vectorisation
arr= np.array([1,2,3,4,5])
print(arr**2)

[ 1  4  9 16 25]


In [20]:
#broadcasting
arr= np.array([1, 2, 3, 4, 5]) 
arr2= np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(arr.shape)
print(arr2.shape)
print(arr + arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [31]:
#normalize
# to normalise the array arr[i]=root of summision(vali-mean)2/n
arr= np.array([[1, 2], [3, 4]])
mean =np.mean(arr)
std_dev = np.std(arr)
normalized_arr= (arr-mean)/std_dev
print(normalized_arr)
print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [33]:
arr=np.array([1,2,3,4,5,6])
print(np.sum(arr))
print(np.prod(arr)) #product 
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))#index of min val
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

21
720
1
6
0
5
3.5
1.707825127659933
3.5
2.9166666666666665


In [41]:
#power function
arr=np.array([1,2,3,4,5,6])
print(np.square(arr))
print(np.pow(arr,3))
print(np.sqrt(arr))
print(np.log(arr))

#rounding the values
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.round(3.14))

arr= np.array([1,2,1,2,3,4,4,5,3,9])
print(np.unique(arr))
print(np.sort(arr))


[ 1  4  9 16 25 36]
[  1   8  27  64 125 216]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
3.0
4.0
3.0
3.0
[1 2 3 4 5 9]
[1 1 2 2 3 3 4 4 5 9]
